// src/frontend-vue/src/views/BoardEdit.vue
<template>
  <section>
    <h1>게시글 수정</h1>

    <div v-if="loading" class="state">불러오는 중입니다...</div>
    <form v-else class="form" @submit.prevent="submit">
      <label>제목</label>
      <input v-model="form.title" maxlength="200" required />

      <label>작성자</label>
      <input
        v-model="form.writer"
        maxlength="50"
        required
        readonly
        class="input-locked"
      />

      <label>내용</label>
      <textarea v-model="form.content" rows="14" required></textarea>

      <!-- ================================================= -->
      <!-- 기존 이미지 미리보기 -->
      <!-- ================================================= -->
      <div v-if="existingImageFiles.length" class="image-gallery">
        <h3>등록된 이미지</h3>

        <div class="image-grid">
          <div
            v-for="file in existingImageFiles"
            :key="file.fileId"
            class="image-item"
            :class="{ 'marked-delete': deleteFileIds.includes(file.fileId) }"
          >
            <img
              v-if="blobUrlMap[file.fileId]"
              :src="blobUrlMap[file.fileId]"
              :alt="file.originalName"
            />
            <div v-else class="image-loading">이미지 불러오는 중...</div>

            <span class="img-name">{{ file.originalName }}</span>

            <label class="delete-check">
              <input
                type="checkbox"
                :checked="deleteFileIds.includes(file.fileId)"
                @change="toggleDelete(file.fileId)"
              />
              삭제
            </label>
          </div>
        </div>
      </div>

      <!-- ================================================= -->
      <!-- 기존 첨부파일 (이미지 제외) -->
      <!-- ================================================= -->
      <div v-if="existingOtherFiles.length" class="files">
        <h3>등록된 첨부파일 ({{ existingOtherFiles.length }})</h3>

        <ul class="file-list">
          <li
            v-for="file in existingOtherFiles"
            :key="file.fileId"
            class="file-item"
            :class="{ 'marked-delete': deleteFileIds.includes(file.fileId) }"
          >
            <span class="file-icon">{{ getFileIcon(file.originalName) }}</span>
            <span class="file-name">{{ file.originalName }}</span>
            <small class="file-size">({{ formatSize(file.fileSize) }})</small>

            <label class="delete-check">
              <input
                type="checkbox"
                :checked="deleteFileIds.includes(file.fileId)"
                @change="toggleDelete(file.fileId)"
              />
              삭제
            </label>
          </li>
        </ul>
      </div>

      <label>추가 첨부파일 (최대 5개)</label>
      <input type="file" multiple @change="onFiles" />
      <div class="selected-files" v-if="selectedFiles.length">
        <span v-for="file in selectedFiles" :key="file.name">
          {{ file.name }}
        </span>
      </div>

      <div class="actions">
        <router-link :to="`/boards/${props.id}`" class="btn">취소</router-link>
        <button class="btn primary" :disabled="saving">
          {{ saving ? "수정 중..." : "수정" }}
        </button>
      </div>
    </form>
  </section>
</template>

<script setup>
import { reactive, ref, computed, onMounted, onUnmounted } from "vue";
import { useRouter } from "vue-router";
import api, { getBoard, updateBoard } from "../api/boardApi";

const props = defineProps({ id: [String, Number] });
const router = useRouter();
const form = reactive({ title: "", content: "", writer: "" });
const selectedFiles = ref([]);
const loading = ref(true);
const saving = ref(false);

/* =========================================================
   기존 첨부파일
========================================================= */
const existingFiles = ref([]);
const deleteFileIds = ref([]);
const blobUrlMap = ref({});

const imageExtensions = ["jpg", "jpeg", "png", "gif", "webp", "svg", "bmp"];

function isImage(file) {
  if (!file.originalName) return false;
  const ext = file.originalName.split(".").pop().toLowerCase();
  return imageExtensions.includes(ext);
}

const existingImageFiles = computed(() => existingFiles.value.filter(isImage));

const existingOtherFiles = computed(() =>
  existingFiles.value.filter((file) => !isImage(file)),
);

function toggleDelete(fileId) {
  const idx = deleteFileIds.value.indexOf(fileId);
  if (idx === -1) {
    deleteFileIds.value.push(fileId);
  } else {
    deleteFileIds.value.splice(idx, 1);
  }
}

async function loadImageBlobs() {
  Object.values(blobUrlMap.value).forEach((url) => {
    if (url) window.URL.revokeObjectURL(url);
  });
  blobUrlMap.value = {};

  for (const file of existingImageFiles.value) {
    try {
      const response = await api.get(`/boards/download/${file.fileId}`, {
        responseType: "blob",
      });
      blobUrlMap.value[file.fileId] = window.URL.createObjectURL(response.data);
    } catch (e) {
      console.error("[BoardEdit] 이미지 불러오기 실패:", file.originalName, e);
    }
  }
}

function getFileIcon(fileName) {
  if (!fileName) return "📁";
  const ext = fileName.split(".").pop().toLowerCase();

  if (imageExtensions.includes(ext)) return "🖼️";
  if (ext === "pdf") return "📕";
  if (["zip", "rar", "7z", "tar", "gz"].includes(ext)) return "📦";
  if (["doc", "docx", "hwp"].includes(ext)) return "📝";
  if (["xls", "xlsx"].includes(ext)) return "📊";
  if (["ppt", "pptx"].includes(ext)) return "📊";
  return "📎";
}

function formatSize(size) {
  if (!size) return "0 B";
  const units = ["B", "KB", "MB", "GB"];
  let i = 0;
  let n = size;
  while (n >= 1024 && i < units.length - 1) {
    n /= 1024;
    i++;
  }
  return `${n.toFixed(i ? 1 : 0)} ${units[i]}`;
}

/* =========================================================
   새 파일 선택
========================================================= */
function onFiles(e) {
  selectedFiles.value = Array.from(e.target.files).slice(0, 5);
}

/* =========================================================
   게시글 불러오기
========================================================= */
async function load() {
  try {
    const { data } = await getBoard(props.id);
    form.title = data.title ?? "";
    form.content = data.content ?? "";
    form.writer = data.writer ?? "";

    existingFiles.value = data.fileList ?? data.files ?? data.boardFiles ?? [];

    await loadImageBlobs();
  } catch (e) {
    console.error("게시글 불러오기 실패:", e);
    alert("게시글을 불러오지 못했습니다.");
    router.push("/boards");
  } finally {
    loading.value = false;
  }
}

/* =========================================================
   수정 제출
========================================================= */
async function submit() {
  if (selectedFiles.value.length > 5) {
    alert("첨부파일은 최대 5개까지 등록 가능합니다.");
    return;
  }

  saving.value = true;
  try {
    const formData = new FormData();

    const boardDto = {
      title: form.title,
      content: form.content,
      writer: form.writer,
    };

    formData.append(
      "board",
      new Blob([JSON.stringify(boardDto)], { type: "application/json" }),
    );

    selectedFiles.value.forEach((file) => {
      formData.append("files", file);
    });

    // 삭제할 기존 파일 ID들 (RequestParam List<Long> deleteFileIds로 매핑됨)
    deleteFileIds.value.forEach((id) => {
      formData.append("deleteFileIds", id);
    });

    await updateBoard(props.id, formData);

    alert("게시글이 수정되었습니다.");
    router.push(`/boards/${props.id}`);
  } catch (e) {
    console.error("게시글 수정 실패 상세:", e.response || e);

    const errorMsg =
      typeof e.response?.data === "string"
        ? e.response.data
        : e.response?.data?.message || "수정에 실패했습니다.";

    alert(errorMsg);
  } finally {
    saving.value = false;
  }
}

onUnmounted(() => {
  Object.values(blobUrlMap.value).forEach((url) => {
    if (url) window.URL.revokeObjectURL(url);
  });
});

onMounted(load);
</script>

<style scoped>
.input-locked {
  background-color: #f2f2f2;
  color: #666;
  cursor: not-allowed;
}
.selected-files {
  margin-top: 8px;
  font-size: 0.9em;
  color: #555;
}

/* =========================================================
   기존 이미지
========================================================= */
.image-gallery {
  margin: 20px 0;
}

.image-gallery h3 {
  font-size: 1em;
  margin-bottom: 10px;
  color: #333;
}

.image-grid {
  display: flex;
  flex-wrap: wrap;
  gap: 16px;
}

.image-item {
  display: flex;
  flex-direction: column;
  width: 220px;
  border: 1px solid #e2e8f0;
  border-radius: 8px;
  overflow: hidden;
  background-color: #fafafa;
  transition: opacity 0.2s;
}

.image-item.marked-delete {
  opacity: 0.4;
}

.image-item img {
  width: 100%;
  height: 160px;
  object-fit: cover;
  display: block;
}

.image-loading {
  width: 100%;
  height: 160px;
  display: flex;
  align-items: center;
  justify-content: center;
  color: #64748b;
  background: #f1f5f9;
}

.img-name {
  padding: 6px 10px;
  font-size: 0.8em;
  color: #555;
  overflow: hidden;
  text-overflow: ellipsis;
  white-space: nowrap;
}

/* =========================================================
   기존 첨부파일
========================================================= */
.files {
  margin: 20px 0;
  padding: 12px 16px;
  background-color: #f8fafc;
  border-radius: 8px;
  border: 1px solid #e2e8f0;
}

.files h3 {
  font-size: 0.95em;
  margin-bottom: 10px;
  color: #475569;
}

.file-list {
  list-style: none;
  padding: 0;
  margin: 0;
}

.file-item {
  display: flex;
  align-items: center;
  gap: 8px;
  margin-bottom: 8px;
  font-size: 0.9em;
}

.file-item.marked-delete {
  opacity: 0.4;
}

.file-size {
  color: #64748b;
}

/* =========================================================
   삭제 체크박스
========================================================= */
.delete-check {
  display: flex;
  align-items: center;
  gap: 4px;
  font-size: 0.8em;
  color: #dc2626;
  padding: 4px 8px;
  cursor: pointer;
}
</style>

// src/frontend/src/pages/BoardEdit.jsx
import React, { useEffect, useState } from "react";
import { useParams, useNavigate } from "react-router-dom";
import axios from "axios";

function BoardEdit() {
  const { id } = useParams();
  const navigate = useNavigate();

  const [form, setForm] = useState({ title: "", content: "", writer: "" });
  const [existingFiles, setExistingFiles] = useState([]);
  const [deleteFileIds, setDeleteFileIds] = useState([]);
  const [newFiles, setNewFiles] = useState([]);
  const [loading, setLoading] = useState(true);
  const [isSubmitting, setIsSubmitting] = useState(false);

  // 💡 파일이 이미지인지 확인하는 헬퍼 함수
  const isImageFile = (fileName) => {
    if (!fileName) return false;
    return /\.(jpg|jpeg|png|gif|webp|svg)$/i.test(fileName);
  };

  useEffect(() => {
    setLoading(true);
    axios
      .get(`/api/boards/${id}`)
      .then((res) => {
        setForm({
          title: res.data.title || "",
          content: res.data.content || "",
          writer: res.data.writer || "",
        });
        setExistingFiles(res.data.fileList || []);
      })
      .catch((err) => {
        console.error("게시글 정보를 불러오지 못했습니다:", err);
        alert("게시글 정보를 불러오는데 실패했습니다.");
        navigate("/");
      })
      .finally(() => {
        setLoading(false);
      });
  }, [id, navigate]);

  // 기존 파일 삭제 지정 토글
  const toggleDeleteFile = (fileId) => {
    if (deleteFileIds.includes(fileId)) {
      setDeleteFileIds(deleteFileIds.filter((fId) => fId !== fileId));
    } else {
      setDeleteFileIds([...deleteFileIds, fileId]);
    }
  };

  // 새로 추가할 파일 선택 처리 (기존 남은 파일 + 신규 파일 <= 5개)
  const handleNewFileChange = (e) => {
    const selected = Array.from(e.target.files);
    const remainingExistingCount = existingFiles.length - deleteFileIds.length;

    if (remainingExistingCount + newFiles.length + selected.length > 5) {
      alert("기존 파일과 합쳐 총 첨부파일은 최대 5개까지 가능합니다.");
      e.target.value = "";
      return;
    }

    setNewFiles((prev) => [...prev, ...selected]);
    e.target.value = "";
  };

  // 새로 선택한 파일 삭제
  const handleRemoveNewFile = (indexToRemove) => {
    setNewFiles((prev) => prev.filter((_, index) => index !== indexToRemove));
  };

  // 수정 제출
  const handleUpdate = async (e) => {
    e.preventDefault();
    if (!form.title.trim() || !form.content.trim()) {
      alert("제목과 내용을 모두 입력해 주세요.");
      return;
    }

    setIsSubmitting(true);

    const formData = new FormData();
    formData.append(
      "board",
      new Blob([JSON.stringify(form)], { type: "application/json" }),
    );

    newFiles.forEach((file) => formData.append("files", file));
    deleteFileIds.forEach((fId) => formData.append("deleteFileIds", fId));

    try {
      await axios.put(`/api/boards/${id}`, formData);
      alert("게시글이 수정되었습니다.");
      navigate(`/detail/${id}`);
    } catch (err) {
      alert("수정 실패: " + (err.response?.data || err.message));
    } finally {
      setIsSubmitting(false);
    }
  };

  if (loading) {
    return (
      <div style={styles.container}>
        <div style={styles.loadingWrapper}>
          <div style={styles.spinner}></div>
          <p style={{ marginTop: "12px", color: "#64748b" }}>
            게시글 데이터를 불러오는 중...
          </p>
        </div>
      </div>
    );
  }

  const activeExistingCount = existingFiles.length - deleteFileIds.length;
  const totalFileCount = activeExistingCount + newFiles.length;

  return (
    <div style={styles.container}>
      {/* 헤더 */}
      <div style={styles.header}>
        <h2 style={styles.title}>✏️ 게시글 수정</h2>
        <p style={styles.subtitle}>
          수정할 내용과 첨부파일을 확인 및 변경해 주세요.
        </p>
      </div>

      <form onSubmit={handleUpdate} style={styles.form}>
        {/* 제목 & 작성자 */}
        <div style={styles.row}>
          <div style={{ ...styles.inputGroup, flex: 2 }}>
            <label style={styles.label}>
              제목 <span style={styles.required}>*</span>
            </label>
            <input
              type="text"
              value={form.title}
              onChange={(e) => setForm({ ...form, title: e.target.value })}
              style={styles.input}
            />
          </div>

          <div style={{ ...styles.inputGroup, flex: 1 }}>
            <label style={styles.label}>작성자</label>
            <input
              type="text"
              value={form.writer}
              disabled
              style={{
                ...styles.input,
                backgroundColor: "#f1f5f9",
                color: "#64748b",
              }}
            />
          </div>
        </div>

        {/* 내용 */}
        <div style={styles.inputGroup}>
          <label style={styles.label}>
            내용 <span style={styles.required}>*</span>
          </label>
          <textarea
            rows="12"
            value={form.content}
            onChange={(e) => setForm({ ...form, content: e.target.value })}
            style={styles.textarea}
          />
        </div>

        {/* 1. 기존 첨부파일 목록 및 삭제 지정 */}
        <div style={styles.fileSection}>
          <div style={styles.fileHeader}>
            <label style={styles.label}>
              기존 첨부파일 ({existingFiles.length})
            </label>
          </div>

          {existingFiles.length > 0 ? (
            <div style={styles.fileList}>
              {existingFiles.map((f) => {
                const isMarkedDelete = deleteFileIds.includes(f.fileId);
                const isImg = isImageFile(f.originalName);

                return (
                  <div
                    key={f.fileId}
                    style={{
                      ...styles.fileItem,
                      backgroundColor: isMarkedDelete ? "#fef2f2" : "#ffffff",
                      borderColor: isMarkedDelete ? "#fca5a5" : "#e2e8f0",
                    }}
                  >
                    <div style={styles.fileInfoGroup}>
                      {/* 🖼️ 기존 이미지 미리보기 */}
                      {isImg && (
                        <img
                          src={`/api/boards/download/${f.fileId}`}
                          alt={f.originalName}
                          style={{
                            ...styles.previewImage,
                            opacity: isMarkedDelete ? 0.4 : 1,
                          }}
                        />
                      )}
                      <span
                        style={{
                          ...styles.fileName,
                          textDecoration: isMarkedDelete
                            ? "line-through"
                            : "none",
                          color: isMarkedDelete ? "#ef4444" : "#1e293b",
                        }}
                      >
                        {isImg ? "🖼️" : "📁"} {f.originalName}
                      </span>
                    </div>

                    <button
                      type="button"
                      onClick={() => toggleDeleteFile(f.fileId)}
                      style={
                        isMarkedDelete
                          ? styles.cancelDeleteBtn
                          : styles.markDeleteBtn
                      }
                    >
                      {isMarkedDelete ? "삭제 취소" : "삭제 선택"}
                    </button>
                  </div>
                );
              })}
            </div>
          ) : (
            <p style={styles.emptyText}>기존 첨부파일이 없습니다.</p>
          )}
        </div>

        {/* 2. 신규 파일 추가 */}
        <div style={styles.fileSection}>
          <div style={styles.fileHeader}>
            <label style={styles.label}>
              추가 첨부파일{" "}
              <span style={styles.fileCount}>({totalFileCount}/5)</span>
            </label>
            <label
              htmlFor="new-file-upload"
              style={
                totalFileCount >= 5
                  ? styles.uploadBtnDisabled
                  : styles.uploadBtn
              }
            >
              📎 파일 선택
            </label>
            <input
              id="new-file-upload"
              type="file"
              multiple
              disabled={totalFileCount >= 5}
              onChange={handleNewFileChange}
              style={{ display: "none" }}
            />
          </div>

          {newFiles.length > 0 && (
            <div style={styles.fileList}>
              {newFiles.map((file, index) => {
                const isImg = isImageFile(file.name);
                const previewUrl = isImg ? URL.createObjectURL(file) : null;

                return (
                  <div key={index} style={styles.fileItem}>
                    <div style={styles.fileInfoGroup}>
                      {/* 🖼️ 신규 선택 이미지 미리보기 */}
                      {isImg && previewUrl && (
                        <img
                          src={previewUrl}
                          alt={file.name}
                          style={styles.previewImage}
                          onLoad={() => URL.revokeObjectURL(previewUrl)} // 메모리 누수 방지
                        />
                      )}
                      <span style={styles.fileName}>
                        ✨ [신규] {file.name}{" "}
                        <span style={styles.fileSize}>
                          ({(file.size / 1024).toFixed(1)} KB)
                        </span>
                      </span>
                    </div>

                    <button
                      type="button"
                      onClick={() => handleRemoveNewFile(index)}
                      style={styles.removeFileBtn}
                    >
                      ✕
                    </button>
                  </div>
                );
              })}
            </div>
          )}
        </div>

        {/* 하단 버튼 */}
        <div style={styles.buttonGroup}>
          <button
            type="button"
            onClick={() => navigate(`/detail/${id}`)}
            style={styles.cancelBtn}
          >
            취소
          </button>
          <button
            type="submit"
            disabled={isSubmitting}
            style={isSubmitting ? styles.submitBtnDisabled : styles.submitBtn}
          >
            {isSubmitting ? "저장 중..." : "수정 완료"}
          </button>
        </div>
      </form>
    </div>
  );
}

// 🎨 스타일 객체 (미리보기 이미지 관련 스타일 추가)
const styles = {
  container: {
    maxWidth: "800px",
    margin: "40px auto",
    padding: "36px",
    backgroundColor: "#ffffff",
    borderRadius: "12px",
    boxShadow: "0 4px 20px rgba(0, 0, 0, 0.08)",
    fontFamily: "'Pretendard', -apple-system, BlinkMacSystemFont, sans-serif",
  },
  header: {
    marginBottom: "28px",
    borderBottom: "1px solid #f1f5f9",
    paddingBottom: "16px",
  },
  title: {
    margin: 0,
    fontSize: "22px",
    fontWeight: "700",
    color: "#0f172a",
  },
  subtitle: {
    margin: "6px 0 0 0",
    fontSize: "14px",
    color: "#64748b",
  },
  form: {
    display: "flex",
    flexDirection: "column",
    gap: "20px",
  },
  row: {
    display: "flex",
    gap: "16px",
  },
  inputGroup: {
    display: "flex",
    flexDirection: "column",
    gap: "6px",
  },
  label: {
    fontSize: "14px",
    fontWeight: "600",
    color: "#334155",
  },
  required: {
    color: "#ef4444",
  },
  input: {
    padding: "10px 14px",
    borderRadius: "8px",
    border: "1px solid #cbd5e1",
    fontSize: "14px",
    outline: "none",
    boxSizing: "border-box",
  },
  textarea: {
    padding: "12px 14px",
    borderRadius: "8px",
    border: "1px solid #cbd5e1",
    fontSize: "14px",
    outline: "none",
    resize: "vertical",
    fontFamily: "inherit",
    boxSizing: "border-box",
  },
  fileSection: {
    backgroundColor: "#f8fafc",
    padding: "16px",
    borderRadius: "8px",
    border: "1px solid #e2e8f0",
  },
  fileHeader: {
    display: "flex",
    justifyContent: "space-between",
    alignItems: "center",
  },
  fileCount: {
    fontSize: "13px",
    fontWeight: "normal",
    color: "#64748b",
  },
  uploadBtn: {
    backgroundColor: "#ffffff",
    border: "1px solid #cbd5e1",
    padding: "6px 12px",
    borderRadius: "6px",
    fontSize: "13px",
    fontWeight: "500",
    color: "#334155",
    cursor: "pointer",
  },
  uploadBtnDisabled: {
    backgroundColor: "#f1f5f9",
    border: "1px solid #e2e8f0",
    padding: "6px 12px",
    borderRadius: "6px",
    fontSize: "13px",
    color: "#94a3b8",
    cursor: "not-allowed",
  },
  fileList: {
    marginTop: "12px",
    display: "flex",
    flexDirection: "column",
    gap: "8px",
  },
  fileItem: {
    display: "flex",
    justifyContent: "space-between",
    alignItems: "center",
    padding: "8px 12px",
    borderRadius: "6px",
    border: "1px solid #e2e8f0",
    transition: "all 0.2s",
  },
  fileInfoGroup: {
    display: "flex",
    alignItems: "center",
    gap: "10px",
  },
  previewImage: {
    width: "48px",
    height: "48px",
    objectFit: "cover",
    borderRadius: "6px",
    border: "1px solid #cbd5e1",
  },
  fileName: {
    fontSize: "13px",
  },
  fileSize: {
    color: "#94a3b8",
    fontSize: "12px",
  },
  emptyText: {
    margin: "10px 0 0 0",
    fontSize: "13px",
    color: "#94a3b8",
  },
  markDeleteBtn: {
    backgroundColor: "#ffffff",
    border: "1px solid #fca5a5",
    color: "#ef4444",
    padding: "4px 8px",
    borderRadius: "4px",
    fontSize: "12px",
    cursor: "pointer",
  },
  cancelDeleteBtn: {
    backgroundColor: "#ef4444",
    border: "none",
    color: "#ffffff",
    padding: "4px 8px",
    borderRadius: "4px",
    fontSize: "12px",
    cursor: "pointer",
  },
  removeFileBtn: {
    background: "none",
    border: "none",
    color: "#ef4444",
    cursor: "pointer",
    fontSize: "14px",
    padding: "0 4px",
  },
  buttonGroup: {
    display: "flex",
    justifyContent: "flex-end",
    gap: "10px",
    marginTop: "12px",
  },
  cancelBtn: {
    padding: "10px 20px",
    borderRadius: "8px",
    border: "1px solid #cbd5e1",
    backgroundColor: "#ffffff",
    color: "#475569",
    fontSize: "14px",
    fontWeight: "600",
    cursor: "pointer",
  },
  submitBtn: {
    padding: "10px 24px",
    borderRadius: "8px",
    border: "none",
    backgroundColor: "#2563eb",
    color: "#ffffff",
    fontSize: "14px",
    fontWeight: "600",
    cursor: "pointer",
  },
  submitBtnDisabled: {
    padding: "10px 24px",
    borderRadius: "8px",
    border: "none",
    backgroundColor: "#93c5fd",
    color: "#ffffff",
    fontSize: "14px",
    fontWeight: "600",
    cursor: "not-allowed",
  },
  loadingWrapper: {
    padding: "60px 0",
    textAlign: "center",
  },
  spinner: {
    width: "32px",
    height: "32px",
    border: "4px solid #e2e8f0",
    borderTop: "4px solid #2563eb",
    borderRadius: "50%",
    margin: "0 auto",
    animation: "spin 1s linear infinite",
  },
};

export default BoardEdit;
